@startuml controller states

state Develop #LightGreen: Build-up production
state Rebuild #LightGreen: Rebuild economy after losses
state Defend #LightGreen: Defend against attacks
state BuildUp #LightGreen: Build an army that\ncounters enemy strategy

state ExpandPrepare #LightBlue: Selecting expand location\nand preparing forces to\nsecure it
state ExpandSecure #LightBlue: Move to selected location\nand secure it
state ExpandBuild #LightBlue: Build expand\non secured location
state ExpandDefend #LightBlue: Defend against attacks

state Exterminate #LightCoral: Attack the enemy

[*] --> Develop: Initial state

Defend --> Rebuild: Attack countered\nDamage is not severe
Defend --> Develop: Attack countered\nDamage is too severe

Develop --> BuildUp: Economy\nfunctioning
Develop --> Defend: Attacked
Develop -left-> ExpandPrepare: Not enough resources to\nproduce estimated army

BuildUp -down-> Exterminate: Army gathered\nOR\nTimeout Exceeded
BuildUp --> Defend: Attacked
BuildUp --> Develop: Impossible to produce\nany combat unit

Rebuild --> BuildUp: Economy\nRestored
Rebuild --> Defend: Attacked

ExpandPrepare --> ExpandSecure: Forces gathered
ExpandPrepare -left-> ExpandDefend: Attacked

ExpandSecure --> ExpandBuild: Expand secured
ExpandSecure -left-> ExpandDefend: Attacked

ExpandBuild --> Develop: Expand build and functioning
ExpandBuild -left-> ExpandDefend: Attacked

ExpandDefend --> ExpandPrepare: Attack Countered\nDamage is not severe
ExpandDefend --> Develop: Attack Countered\nDamage is too severe

Exterminate --> [*]: Enemy defeated
Exterminate --> Develop: Army slain\nOR\nTimeout exceeded
Exterminate --> Defend: Main or expand attacked


legend
| **Color** | **Meaning** |
|<#LightGreen>| Exploit |
|<#LightBlue>| Expand |
|<#LightCoral>| Exterminate |
endlegend

@enduml